import java.util.Properties

plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

val releaseSigningPropertiesFile = rootProject.file("key.properties")
val releaseSigningProperties = Properties().apply {
    if (releaseSigningPropertiesFile.isFile) {
        releaseSigningPropertiesFile.inputStream().use(::load)
    }
}
val hasReleaseSigning = listOf(
    "storeFile",
    "storePassword",
    "keyAlias",
    "keyPassword",
).all { !releaseSigningProperties.getProperty(it).isNullOrBlank() }

android {
    namespace = "com.example.ai_blind_assistant"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId = "com.example.ai_blind_assistant"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    // Prevent TFLite model from being compressed in APK.
    aaptOptions {
        noCompress += "tflite"
    }

    signingConfigs {
        if (hasReleaseSigning) {
            create("release") {
                storeFile = file(releaseSigningProperties.getProperty("storeFile"))
                storePassword = releaseSigningProperties.getProperty("storePassword")
                keyAlias = releaseSigningProperties.getProperty("keyAlias")
                keyPassword = releaseSigningProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            signingConfig = if (hasReleaseSigning) {
                signingConfigs.getByName("release")
            } else {
                // Keeps local release builds installable before an owner creates
                // the ignored project keystore. Distribution must use the
                // release config generated by scripts/configure_release_signing.sh.
                signingConfigs.getByName("debug")
            }
            isMinifyEnabled = false
            isShrinkResources = false
        }
    }
}

androidComponents {
    onVariants(selector().withBuildType("debug")) { variant ->
        // Keep symbols in debug APKs so local development does not depend on
        // the NDK's llvm-strip executable.
        variant.packaging.jniLibs.keepDebugSymbols.add("**/*.so")
    }
}

dependencies {
    // 2.1.6 currently publishes litert and litert-api with the same Android
    // namespace, which AGP 9 rejects during manifest merging. 2.1.5 is the
    // latest verified monolithic runtime artifact for this project.
    implementation("com.google.ai.edge.litert:litert:2.1.5") {
        // The app uses only the bundled Interpreter/native runtime. Exclude
        // optional Play AI-delivery and lifecycle dependencies so no remote
        // model-delivery or background-work stack enters the offline APK.
        isTransitive = false
    }

    // Bundled offline speech fallback for Android devices whose vendor image
    // does not provide the dedicated API 31+ on-device recognition service.
    // Vosk's official Android demo uses these current Maven Central artifacts.
    implementation("net.java.dev.jna:jna:5.18.1@aar")
    implementation("com.alphacephei:vosk-android:0.3.75@aar")

    testImplementation("junit:junit:4.13.2")
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
